import Head from "next/head"
import Footer from "./footer"
import Header from "./header"


export default function Layout({title, children}){

    return(
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/s-24.png" />
            </Head>
            <Header />
            <main>
                { children }
            </main>
            <Footer />
        </>
    )
}